name: 🖥️ Release backend
on:
  push:
    branches: [ master ]
    paths:
      - 'api/**'
  workflow_dispatch:

env:
  appName: questions

jobs:
  deploy-api:
    runs-on: ubuntu-latest
    environment: hetzner
    steps:
      - uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t ${{ secrets.DOCKER_IMAGE_NAME }}:${{ github.run_number }} ${{ secrets.DOCKER_IMAGE_NAME }}:latest .
      - run: docker push ${{ secrets.DOCKER_IMAGE_NAME }} --all-tags
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            podman auto-update
