
name: Keep API alive
on:
 schedule:
   - cron: '*/30 * * * *'
 workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: curl -I https://bogdbo-questions-api.herokuapp.com/graphql
